export const jobData = [
  {
    id: 1,
    jobTitle: "Senior Full Stack Web Developer (MERN)",
    jobDescription:
      "We are seeking a Senior Full Stack Web Developer with expertise in the MERN (MongoDB, Express, React, Node.js) stack and familiar with Next.js, TypeScript, Redux, and Prisma. 2.5–3 years of hands-on experience building and maintaining full-stack applications. The ideal candidate will have a strong understanding of both front-end and in-depth understanding of server-side development, excellent problem-solving skills, and the ability to collaborate effectively with team members.",
    aboutUs:
      "SM IT Solution is a leading technology company based in Bangladesh and the UAE, specialising in innovative digital solutions. We focus on delivering high-impact results for our clients. We are seeking a passionate Senior Full Stack Developer to join our team and contribute to the success of a variety of exciting projects.",
    responsibilities: [
      "Collaborate with cross-functional teams to Design, develop, and maintain scalable web applications using the MERN stack.",
      "Develop new user-facing features using React.js and Next.js while ensuring high performance and responsiveness.",
      "Implement TypeScript for type safety and improved code quality in both front-end and back-end codebase.",
      "Manage complex application state using Redux for optimal performance.",
      "Develop and integrate RESTful APIs and server-side functionality with Node.js and Express.",
      "Integrate third-party services and APIs to enhance platform functionality.",
      "Collaborate with designers and other developers to implement user-friendly UI/UX.",
      "Write clean, efficient, and maintainable code for both front-end and back-end systems.",
      "Participate in code reviews to ensure code quality and consistency.",
      "Optimize server-side architecture for performance, security, and scalability.",
      "Perform comprehensive testing and debugging to ensure application quality and reliability, while troubleshooting and optimizing both client-side and server-side for speed, scalability, and performance.",
      "Ensure web applications are secure, reliable, and adhere to industry standards and best practices.",
    ],
    qualifications: [
      "2.5–3 years of professional experience as a Full Stack Developer, focusing on the MERN stack.",
      "Strong understanding of JavaScript (ES6+), TypeScript, HTML5, CSS3, and front-end frameworks like React and Next.js.",
      "Strong experience in backend development with Node.js, Express, and MongoDB.",
      "Solid understanding of database design, management, and optimization in MongoDB or other NoSQL databases.",
      "Experience with server-side rendering (SSR) and static site generation (SSG) using Next.js is a plus.",
      "Experience with version control systems (e.g., Git) in team-based projects and familiarity with Agile development practices.",
      " Understanding of server-side performance tuning, caching mechanisms, and scalability solutions.",
      "Knowledge of web application security practices (OAuth, JWT, data encryption).",
      "Ability to work independently as well as in a team environment.",
      "Strong problem-solving skills are highly desirable.",
      "Good communication skills and ability to collaborate effectively with team members.",
    ],
    niceToHaveSkills: [
      "Experience with Redux for managing complex state and Prisma for database management and optimization.",
      "Familiarity  with cloud platforms like AWS or Azure, and containerization tools such as Docker.",
      "Knowledge of GraphQL, WebSockets, and real-time data processing.",
      "Understanding of cybersecurity principles and data protection.",
    ],
    officeTime: "11:00 AM - 7:00 PM",
    vacancy: 1,
    education: "Bachelor's or Master's degree in Computer Science or a related field from a recognized university is preferred. However, we are open to considering candidates with exceptional experience in lieu of formal qualifications.",
    jobType: "On-site",
    jobCategory: "Full Time",
    experience: " 3 - 5 years",
    workDays: "Sat - Thu (Friday Off)",
    deadline: "30 April, 2025",
    salary: "TK 70-100K (Based on experience)",
    location: "Chittagong, Bangladesh",
  },
  {
    id: 2,
    jobTitle: "Full Stack (MERN) Web Developer Intern",
    jobDescription:
      "SM IT Solutions is looking for some motivated and enthusiastic Full Stack (MERN) Web Developer Interns to join our dynamic team. This is a full-time, onsite internship opportunity for passionate developers looking to gain hands-on experience in web development.",
    aboutUs:
      "SM IT Solution is a leading technology company based in Bangladesh and the UAE, specialising in innovative digital solutions. We focus on delivering high-impact results for our clients. We are seeking a passionate Senior Full Stack Developer to join our team and contribute to the success of a variety of exciting projects.",
    responsibilities: [
      "Collaborate with the development team to build and maintain web applications using the MERN stack.",
      "Develop user-friendly front-end components using React.js & Next.js.",
      "Implement back-end APIs and server-side logic using Node.js and Express.",
      "Integrate databases with MongoDB to ensure data storage and retrieval functionality.",
      "Stay updated with the latest web development trends and best practices.",

    ],
    qualifications: [
      "Experience in UI design or familiarity with Figma will be a big plus. ",
      "Strong understanding of HTML, CSS, and JavaScript. ",
      "Experience with React.js and Node.js is a plus. ",
      "Basic understanding of MongoDB and Express.js. ",
      "A good grasp of version control tools, particularly Git. ",
      "Ability to work in a collaborative team environment. ",
      "Strong problem-solving and analytical skills. ",
      "Willingness to learn and adapt to new technologies.",
      "Excellent communication skills and attention to detail. ",

    ],
    niceToHaveSkills: [
      "Experience with Redux for managing complex state and Prisma for database management and optimization.",
      "Experience in UI design or familiarity with Figma will be a big plus.",

    ],
    officeTime: "11:00 AM - 7:00 PM",
    vacancy: 4,
    education: "Bachelor's degree in Computer Science or a related field from a recognized university is preferred. However, we are open to considering candidates with exceptional experience in lieu of formal qualifications.",
    jobType: "On-site",
    jobCategory: "Full Time",
    experience: " 0 - 1 years",
    workDays: "Sat - Thu (Friday Off)",
    deadline: "25 April, 2025",
    salary: "TK 10K - 15k",
    location: "Chittagong, Bangladesh",
  },
  {
    id: 3,
    jobTitle: "Digital Marketing Specialist",
    jobDescription:
      "The Digital Marketing Specialist will focus on managing online marketing strategies, analyzing data to optimize campaigns, and increasing brand awareness. You will be tasked with planning and executing digital marketing campaigns, including web, SEO/SEM, email, social media, and display advertising. You will also analyze and report on campaign performance.",
    responsibilities: [
      "Develop and execute digital marketing strategies.",
      "Manage SEO and SEM strategies.",
      "Analyze and optimize advertising campaigns.",
      "Create content for social media platforms.",
      "Collaborate with the sales team for better results.",
      "Track and report website traffic and social media performance.",
    ],
    qualifications: [
      "Experience with SEO, Google Analytics, and SEM.",
      "Proficient in social media marketing.",
      "Strong analytical and project management skills.",
      "Excellent communication and teamwork skills.",
    ],
    officeTime: "11:00 AM - 7:00 PM",
    vacancy: 2,
    education: "Bachelor's or Master's degree in Computer Science or a related field from a recognized university is preferred.However, we are open to considering candidates with exceptional experience in lieu of formal qualifications.",
    salary: "TK 20-45k (Based on experience)",
    jobType: "On-site",
    jobCategory: "Full Time",
    experience: " 2 years",
    workDays: "Sat - Thu (Friday Off)",
    deadline: "30 October, 2024",
    location: "Chittagong, Bangladesh",
  },
  {
    id: 4,
    jobTitle: "Sales Representative",
    jobDescription:
      "We are seeking an energetic and approachable Sales Representative who is confident in front of the camera to engage with customers through live presentations. The ideal candidate should possess excellent communication skills, be able to build relationships with potential clients and demonstrate a passion for driving sales through engaging content and high-quality customer service.",
    responsibilities: [
      "Conduct live sessions to promote and sell products to online audiences.",
      "Interact with viewers, answer questions, and encourage purchases during live streams.",
      "Develop and maintain strong relationships with customers.",
      "Handle customer inquiries through phone, live chat, and social media.",
      "Collaborate with the team to plan and execute engaging and effective live presentations.",
    ],
    qualifications: [
      "Comfortable in front of the camera with a confident and engaging on-screen presence.",
      "Strong communication and interpersonal skills.",
      "Knowledge of online content strategy.",
      "Previous experience in sales or customer service is a plus.",
      "Enthusiasm for customer engagement and product promotion.",
      "Able to work independently and within a team environment.",
      "Age: Not more than 30 years old.",
    ],
    officeTime: "11:00 AM - 7:00 PM",
    education: "Minimum of graduation in any discipline. However, we are open to considering candidates with exceptional experience in lieu of formal qualifications.",
    vacancy: 1,
    jobType: "On-site",
    jobCategory: "Full-time",
    experience: " 1 years",
    salary: "Negotiable",
    workDays: "Sat - Thu (Friday Off)",
    deadline: "26 October, 2024",
    location: "Chittagong, Bangladesh",
  },
];
